/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useDepthBuffer } from "@react-three/drei";
import { useFrame, useThree } from "react-three-fiber";
// import Mouselight from "./MouseLight";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./skull.gltf");
  const lightRef = useRef();

  // make light follow mouse

  console.log(lightRef);

  const { viewport } = useThree();

  useFrame(({ mouse }) => {
    const x = (mouse.x * viewport.width) / 2;
    const y = (mouse.y * viewport.height) / 2;
    lightRef.current.position.set(x, y, 1);
    lightRef.current.rotation.set(-y, x, 0);
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <pointLight
        ref={lightRef}
        distance={70}
        decay={0}
        intensity={0.09}
        color={"#e0ffda"}
      />

      <group
        position={[0.08, 0.7, 0]}
        rotation={[-0.95, -1.565, 1.9]}
        scale={[-0.27, -0.39, -0.18]}
      >
        <mesh
          geometry={nodes.Cube147.geometry}
          material={materials.bone_white}
        />
        <mesh
          geometry={nodes.Cube147_1.geometry}
          material={materials.bone_dark001}
        />
        <mesh
          geometry={nodes.Cube147_2.geometry}
          material={materials["skin.001"]}
        />
        <mesh geometry={nodes.Cube147_3.geometry} material={materials.sk} />
        <mesh
          geometry={nodes.Cube147_4.geometry}
          material={materials["bone_whitex.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/skull.gltf");
