import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import PortfolioPiece from "../components/PortfolioPiece";

const URL = process.env.STRAPIBASEURL;

export async function getStaticProps(context) {
  const fetchParams = {
    method: "post",
    headers: {
      "content-type": "application/json",
    },
    body: JSON.stringify({
      query: `{
        portfoliopieces{
          data{
            attributes{
              title
              description
              techstack
              livesite
              repo
              image {
                data{
                  attributes{
                    url
                  }
                }
              }
            }
          }
        }
        }`,
    }),
  };

  const res = await fetch(`${URL}/graphql`, fetchParams);
  const data = await res.json();

  return {
    props: data,
  };
}

export default function Home({ data }) {
  console.log(data.portfoliopieces.data);

  const portfolioElements = data.portfoliopieces.data.map((piece) => {
    return (
      <PortfolioPiece
        key={piece.attributes.title}
        title={piece.attributes.title}
        description={piece.attributes.description}
        techstack={piece.attributes.techstack}
        livesite={piece.attributes.livesite}
        repo={piece.attributes.repo}
        image={piece.attributes.image}
      />
    );
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="portfolioList">{portfolioElements}</section>
    </div>
  );
}
